export const SET_FILTER = "SET_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_FILTER_BY_TITLE = "SET_FILTER_BY_TITLE";
export const SET_FILTER_BY_CATEGORY = "SET_FILTER_BY_CATEGORY";
export const SET_FILTER_BY_TAG = "SET_FILTER_BY_TAG";
export const SET_FILTER_BY_AUTHOR = "SET_FILTER_BY_AUTHOR";
export const SET_FILTER_BY_DATE = "SET_FILTER_BY_DATE";
export const SET_FILTER_BY_RECENT = "SET_FILTER_BY_RECENT";
